In [1]:
import pandas as pd
from modules.data_hourly_preprocessing import DataCleaner

In [2]:
TARGET_COL ="pm25"
HORIZON = 24

In [3]:
fecheck_df= pd.read_parquet(r"D:\pypipeline\data\processed\hourly\us_paro_hourly\test_processed.parquet")

features_exclude = [f"{TARGET_COL}_plus_{i}h" for i in range(1, HORIZON + 1)] + \
                       [f"o3_plus_{i}h" for i in range(1, HORIZON + 1)] + \
                       [f"pm25_plus_{i}h" for i in range(1, HORIZON + 1)] + \
                       ["segment_id", "imputation_confidence"]

In [4]:
fecheck_df =fecheck_df.drop(columns=features_exclude)

In [5]:
fecheck_df.head()

,pm25,o3,pm25_target,o3_target,hour,day_of_week,is_weekend,is_night,pm25_missing,o3_missing,...,o3_roll_6,pm25_roll_12,o3_roll_12,pm25_roll_24,o3_roll_24,pm25_slope_3h,o3_slope_3h,pm25_slope_12h,o3_slope_12h,pm25_o3_ratio
date,,,,,,,,,,,,,,,,,,,,,
2020-08-04 10:00:00+05:45,16.0,0.039,16.0,0.039,10,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410.25641
2020-08-04 11:00:00+05:45,16.0,0.039,16.0,0.039,11,1,0,0,0,0,...,0.039,16.0,0.039,16.0,0.039,NaN,NaN,NaN,NaN,410.25641
2020-08-04 12:00:00+05:45,NaN,NaN,NaN,NaN,12,1,0,0,1,1,...,0.039,16.0,0.039,16.0,0.039,NaN,NaN,NaN,NaN,NaN
2020-08-04 13:00:00+05:45,NaN,NaN,NaN,NaN,13,1,0,0,1,1,...,0.039,16.0,0.039,16.0,0.039,NaN,NaN,NaN,NaN,NaN
2020-08-04 14:00:00+05:45,NaN,NaN,NaN,NaN,14,1,0,0,1,1,...,0.039,16.0,0.039,16.0,0.039,NaN,NaN,NaN,NaN,NaN

In [6]:
df = pd.read_csv(r"D:\pypipeline\data\raw\pred_ingestion\us_paro\us_paro_hourly.csv")

In [7]:
df.drop(columns=["pm10"], inplace=True)

In [8]:
df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)

In [9]:
clean = DataCleaner()
df_1 = clean.add_time_features(df)
df_2 = clean.add_missing_flags(df_1)
df_2["was_imputed"]=0
df_3 = clean.add_gap_length(df_2)
df_3 = clean.add_segmentation(df_3)

df_4 = clean.engineer_features(df_3)

2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Adding time-based features
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Adding missing-value flags
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Computing gap length features
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Gap length features added
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Adding segment identifiers
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Segmentation complete
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Engineering features
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Adding lag features
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Adding rolling window features
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Adding slope and ratio features
2026-02-13 21:18:23 | INFO | modules.data_hourly_preprocessing | Feature engineering complete with shape (24, 73)

In [ ]:
df_4.head()

,o3,pm25,hour,day_of_week,is_weekend,is_night,pm25_missing,o3_missing,was_imputed,pm25_gap_length,...,o3_roll_6,pm25_roll_12,o3_roll_12,pm25_roll_24,o3_roll_24,pm25_slope_3h,o3_slope_3h,pm25_slope_12h,o3_slope_12h,pm25_o3_ratio
date,,,,,,,,,,,,,,,,,,,,,
2026-02-09 17:45:00,111.87,124.68,17,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.114508
2026-02-09 18:45:00,99.74,130.26,18,0,0,0,0,0,0,0,...,111.8700,124.6800,111.8700,124.6800,111.8700,NaN,NaN,NaN,NaN,1.305996
2026-02-09 19:45:00,90.10,137.91,19,0,0,0,0,0,0,0,...,105.8050,127.4700,105.8050,127.4700,105.8050,6.615,-10.885,6.615,-10.885,1.530633
2026-02-09 20:45:00,83.94,145.22,20,0,0,0,0,0,0,0,...,100.5700,130.9500,100.5700,130.9500,100.5700,7.480,-7.900,6.927,-9.343,1.730045
2026-02-09 21:45:00,76.66,149.80,21,0,0,0,0,0,0,0,...,96.4125,134.5175,96.4125,134.5175,96.4125,5.945,-6.720,6.520,-8.622,1.954083

In [21]:
import mlflow
mlflow.set_tracking_uri("http://localhost:5000")
model = mlflow.pyfunc.load_model("models:/hourly_pm25_24h_service/latest")

Downloading artifacts: 100%|██████████| 7/7 [00:03<00:00,  2.10it/s]
Downloading artifacts: 100%|██████████| 8/8 [00:00<00:00, 12.62it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 12.21it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 10.06it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 10.05it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:01<00:00,  5.69it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  9.46it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 11.40it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 11.03it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 12.21it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 11.13it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 11.07it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 12.17it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 12.94it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  8.70it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  9.69it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 11.11it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  8.81it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  8.84it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  8.90it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 10.13it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  9.25it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 11.81it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00,  8.03it/s]
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 12.25it/s]

In [26]:
df_4

,o3,pm25,hour,day_of_week,is_weekend,is_night,pm25_missing,o3_missing,was_imputed,pm25_gap_length,...,o3_roll_6,pm25_roll_12,o3_roll_12,pm25_roll_24,o3_roll_24,pm25_slope_3h,o3_slope_3h,pm25_slope_12h,o3_slope_12h,pm25_o3_ratio
0,111.87,124.68,17,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.114508
1,99.74,130.26,18,0,0,0,0,0,0,0,...,111.870000,124.680000,111.870000,124.680000,111.870000,NaN,NaN,NaN,NaN,1.305996
2,90.10,137.91,19,0,0,0,0,0,0,0,...,105.805000,127.470000,105.805000,127.470000,105.805000,6.615,-10.885,6.615000,-10.885000,1.530633
3,83.94,145.22,20,0,0,0,0,0,0,0,...,100.570000,130.950000,100.570000,130.950000,100.570000,7.480,-7.900,6.927000,-9.343000,1.730045
4,76.66,149.80,21,0,0,0,0,0,0,0,...,96.412500,134.517500,96.412500,134.517500,96.412500,5.945,-6.720,6.520000,-8.622000,1.954083
5,64.53,157.65,22,0,0,0,0,0,0,0,...,92.462000,137.574000,92.462000,137.574000,92.462000,6.215,-9.705,6.593714,-8.917143,2.443050
6,53.74,164.13,23,0,0,0,0,0,0,0,...,87.806667,140.920000,87.806667,140.920000,87.806667,7.165,-11.460,6.607857,-9.223214,3.054150
7,44.52,167.12,0,1,0,1,0,0,0,0,...,78.118333,144.235714,82.940000,144.235714,82.940000,4.735,-10.005,6.312262,-9.350476,3.753819
8,36.58,171.74,1,1,0,1,0,0,0,0,...,68.915000,147.096250,78.137500,147.096250,78.137500,3.805,-8.580,6.061500,-9.315833,4.694915
9,29.77,176.30,2,1,0,1,0,0,0,0,...,59.995000,149.834444,73.520000,149.834444,73.520000,4.590,-7.375,5.851939,-9.161515,5.922069
10,23.72,179.29,3,1,0,1,0,0,0,0,...,50.966667,152.481000,69.145000,152.481000,69.145000,3.775,-6.430,5.607545,-8.935909,7.558600
11,18.38,183.25,4,1,0,1,0,0,0,0,...,42.143333,154.918182,65.015455,154.918182,65.015455,3.475,-5.695,5.403182,-8.667448,9.970076
12,13.97,187.70,5,1,0,1,0,0,0,0,...,34.451667,157.279167,61.129167,157.279167,61.129167,4.205,-4.875,5.091434,-8.174860,13.435934
13,10.06,191.50,6,1,0,0,0,0,0,0,...,27.823333,162.530833,52.970833,159.619231,57.501538,4.125,-4.160,4.738776,-7.699406,19.035785
14,7.39,197.88,7,1,0,0,0,0,0,0,...,22.080000,167.634167,45.497500,161.896429,54.112857,5.090,-3.290,4.550979,-7.137692,26.776725
15,15.21,203.33,8,1,0,0,0,0,0,0,...,17.215000,172.631667,38.605000,164.295333,50.998000,5.915,2.575,4.485699,-5.976818,13.368179
16,48.81,194.16,9,1,0,0,0,0,0,0,...,14.788333,177.474167,32.877500,166.735000,48.761250,-1.860,20.710,3.869545,-3.373916,3.977873
17,76.13,201.17,10,1,0,0,0,0,0,0,...,18.970000,181.170833,30.556667,168.348235,48.764118,-1.080,30.460,3.569615,-0.076853,2.642454
18,116.57,219.77,11,1,0,0,0,0,0,0,...,28.595000,184.797500,31.523333,170.171667,50.284444,12.805,33.880,3.975280,4.204021,1.885305
19,178.61,145.26,12,1,0,0,0,0,0,0,...,45.695000,189.434167,36.759167,172.782105,53.773158,-27.955,51.240,1.261993,10.012587,0.813280
20,181.03,123.13,13,1,0,0,0,0,0,0,...,73.786667,187.612500,47.933333,171.406000,60.015000,-48.320,32.230,-1.939580,14.615629,0.680164
21,181.46,117.96,14,1,0,0,0,0,0,0,...,102.726667,183.561667,59.970833,169.107143,65.777619,-13.650,1.425,-4.792797,17.915524,0.650061
22,172.00,120.67,15,1,0,0,0,0,0,0,...,130.435000,178.700000,72.611667,166.782273,71.035909,-1.230,-4.515,-6.997902,19.515804,0.701570
23,152.86,126.58,16,1,0,0,0,0,0,0,...,150.966667,173.815000,84.968333,164.777391,75.425652,4.310,-14.300,-8.385769,19.100280,0.828078

In [28]:
fin = df_4.iloc[1,:]

In [30]:
fin

o3                 99.740000
pm25              130.260000
hour               18.000000
day_of_week         0.000000
is_weekend          0.000000
                     ...
pm25_slope_3h            NaN
o3_slope_3h              NaN
pm25_slope_12h           NaN
o3_slope_12h             NaN
pm25_o3_ratio       1.305996
Name: 1, Length: 73, dtype: float64

In [29]:
model.predict(fin)

MlflowException: Failed to enforce schema of data '<mlflow.pyfunc.model.PythonModelContext object at 0x000002091E2BF170>' with schema '['pm25': double (optional), 'o3': double (optional), 'hour': integer (required), 'day_of_week': integer (required), 'is_weekend': long (required), 'is_night': long (required), 'pm25_missing': long (required), 'o3_missing': long (required), 'pm25_gap_length': long (required), 'o3_gap_length': long (required), 'was_imputed': double (optional), 'hour_sin': double (required), 'hour_cos': double (required), 'pm25_lag_1': double (optional), 'o3_lag_1': double (optional), 'pm25_lag_2': double (optional), 'o3_lag_2': double (optional), 'pm25_lag_3': double (optional), 'o3_lag_3': double (optional), 'pm25_lag_4': double (optional), 'o3_lag_4': double (optional), 'pm25_lag_5': double (optional), 'o3_lag_5': double (optional), 'pm25_lag_6': double (optional), 'o3_lag_6': double (optional), 'pm25_lag_7': double (optional), 'o3_lag_7': double (optional), 'pm25_lag_8': double (optional), 'o3_lag_8': double (optional), 'pm25_lag_9': double (optional), 'o3_lag_9': double (optional), 'pm25_lag_10': double (optional), 'o3_lag_10': double (optional), 'pm25_lag_11': double (optional), 'o3_lag_11': double (optional), 'pm25_lag_12': double (optional), 'o3_lag_12': double (optional), 'pm25_lag_13': double (optional), 'o3_lag_13': double (optional), 'pm25_lag_14': double (optional), 'o3_lag_14': double (optional), 'pm25_lag_15': double (optional), 'o3_lag_15': double (optional), 'pm25_lag_16': double (optional), 'o3_lag_16': double (optional), 'pm25_lag_17': double (optional), 'o3_lag_17': double (optional), 'pm25_lag_18': double (optional), 'o3_lag_18': double (optional), 'pm25_lag_19': double (optional), 'o3_lag_19': double (optional), 'pm25_lag_20': double (optional), 'o3_lag_20': double (optional), 'pm25_lag_21': double (optional), 'o3_lag_21': double (optional), 'pm25_lag_22': double (optional), 'o3_lag_22': double (optional), 'pm25_lag_23': double (optional), 'o3_lag_23': double (optional), 'pm25_lag_24': double (optional), 'o3_lag_24': double (optional), 'pm25_roll_3': double (optional), 'o3_roll_3': double (optional), 'pm25_roll_6': double (optional), 'o3_roll_6': double (optional), 'pm25_roll_12': double (optional), 'o3_roll_12': double (optional), 'pm25_roll_24': double (optional), 'o3_roll_24': double (optional), 'pm25_slope_3h': double (optional), 'o3_slope_3h': double (optional), 'pm25_slope_12h': double (optional), 'o3_slope_12h': double (optional), 'pm25_o3_ratio': double (optional)]'. Error: Expected input to be DataFrame. Found: PythonModelContext